COMPILER = clang
CFLAGS = -Wall -Wextra -Wfloat-equal -Wundef -Wshadow -Wconversion -Wunreachable-code -Wpointer-arith -Wcast-align -Wstrict-prototypes -Wwrite-strings -Wswitch-default -Wswitch-enum -Winit-self

all: signals

signals: signals.c
	${COMPILER} ${CFLAGS} signals.c -o signals.exe

clean:
	rm -f *.exe